version: '3'
services:
  app:
    image: coders/starwars-api
    ports:
      - "8000:8080"
    depends_on:
      - db
  db:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=starwars
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password