spring:
  datasource:
    url: jdbc:postgresql://db:5432/starwars
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  servlet:
    context-path: /api/starwars
