INSERT INTO RESOURCE (NAME, VALUE) VALUES ('WEAPON', 4);
INSERT INTO RESOURCE (NAME, VALUE) VALUES ('BULLET', 3);
INSERT INTO RESOURCE (NAME, VALUE) VALUES ('WATER', 2);
INSERT INTO RESOURCE (NAME, VALUE) VALUES ('FOOD', 1);
